### PR TITLE
*: Port to Jekyll

### PR DESCRIPTION
**Pull request by wking**
Drop Hugo and set things up so you can build by pusing to a GitHub Pages branch.  I've tried hard to not change any of the content, but there are a lot of pieces moving around.

### CODE REVIEW

**Comment by wking** [comment]
Preview up at https://wking.github.io/runc.io/

**Comment by caniszczyk** [comment]
Thanks @wking, next step is to submit this as a PR to https://github.com/opencontainers/runc

I'd probably put it in the web/ folder and after that, we'd have to make some changes about how we configure gh-pages + the CNAME alias

**Comment by wking** [comment]
> next step is to submit this as a PR to https://github.com/opencontainers/runc

Do we want to review the [other two PRs][1] first?

> I'd probably put it in the web/ folder...

Why not just pull this Repo's master branch into runC as a gh-pages branch?

[1]: https://github.com/opencontainers/runc.io/pulls

**Comment by caniszczyk** [comment]
@wking because GitHub now supports this workflow and it aids discoverability of the web page (which makes it easier to contribute IMHO than hiding it in a gh-pages branch).

Thanks for doing this work, we are one step closer to deleting this repo :)

**Comment by caniszczyk** [comment]
@wking in regards to the other two PRs, lets just shelve them for now until we have the site moved and migrated, than we can make changes and follow the typical OCI dev process

**Comment by wking** [comment]
On Sun, Jan 29, 2017 at 03:04:09PM -0800, Chris Aniszczyk wrote:
> @wking because GitHub now supports this workflow and it aids
> discoverability of the web page (which makes it easier to contribute
> IMHO than hiding it in a gh-pages branch).

On the other hand, developing the website is fairly separate to
developing the code itself.  And @cyphar (the only runC maintainer
who's opinion I'm aware of) has previously said that he preferred to
keep the website source out of runC's master [1].  If it was up to me
(and it's not, I have no stake in this at all), I'd leave the website
source in the master branch of this repo and have a distinct
maintainer-set (seeded by any current runC maintainers who are
interested) to maintain it.

And you can help with discovery by putting up the usual “Fork me on
GitHub” ribbon [2] and mentioning the location of the Jekyll source in
CONTRIBUTING.md (wherever you choose to put that source).

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/JEOOUi59-SU/irWxIdj2EAAJ
     Subject: Re: runC hamster copyright holder?
     Date: Wed, 14 Dec 2016 10:54:51 +1100
     Message-ID: <af550345-b644-deaa-2c49-c3bbc8d9b3fd@suse.de>
[2]: https://github.com/blog/273-github-ribbons

**Comment by cyphar** [comment]
I don't want this repo to be put inside `runc`'s **master** branch. Because that will just pollute the history of runC with the website code. If you _really_ want it to be in a `gh-pages` branch that has a completely separate history we can do that, but I would prefer that we keep the two pieces of code separate.

**Comment by cyphar** [comment]
Because it will also mix up PRs for runC with PRs for the website.

**Comment by caniszczyk** [comment]
That's fair @cyphar, it's really up for the @opencontainers/runc-maintainers to decide how they want to do things. I'm fine with it in the gh-pages branch, as long as things are just in one repo now.

**Comment by wking** [comment]
> ... it's really up for the @opencontainers/runc-maintainers to decide how they want to do things.

It makes sense to ask them if/how they want to take ownership of runc.io.  If fewer than 2/3 of runC maintainers approve adopting it, then it's up to the TOB if they want to start a new OCI Project to maintain runc.io.

@cyphar, maybe it would help if you propose a motion to bring runc.io under the runC OCI Project however makes sense to you and put it to a runC-maintainer vote?

**Pull request merged**
